package main

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/Rin0530/DinnerDecider/backend/internal/handler"
	"github.com/Rin0530/DinnerDecider/backend/internal/repository"
	"github.com/Rin0530/DinnerDecider/backend/internal/service"
	"github.com/Rin0530/DinnerDecider/backend/internal/usecase"
	"github.com/Rin0530/DinnerDecider/backend/pkg/config"
	"github.com/Rin0530/DinnerDecider/backend/pkg/database"
	"github.com/Rin0530/DinnerDecider/backend/pkg/logger"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/Rin0530/DinnerDecider/backend/docs" // docs is generated by Swag CLI
)

// @title           Dinner Decider API
// @version         1.0
// @description     This is an API server for the Dinner Decider application.
// @host            localhost:8080
// @BasePath        /api
// @schemes         http

func main() {
	// Load configuration
	cfg, err := config.Load("")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to load configuration: %v\n", err)
		os.Exit(1)
	}

	// Initialize logger
	if err := logger.Init(cfg.Logging.Level, cfg.Logging.Format); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to initialize logger: %v\n", err)
		os.Exit(1)
	}

	logger.Info("Starting refrigerator API server...")

	// Connect to database
	dbConfig := database.Config{
		Host:         cfg.Database.Host,
		Port:         cfg.Database.Port,
		User:         cfg.Database.User,
		Password:     cfg.Database.Password,
		DBName:       cfg.Database.DBName,
		MaxOpenConns: cfg.Database.MaxOpenConns,
		MaxIdleConns: cfg.Database.MaxIdleConns,
	}

	db, err := database.NewConnection(dbConfig)
	if err != nil {
		logger.Fatalf("Failed to connect to database: %v", err)
	}
	defer database.Close(db)

	// Initialize dependencies (Dependency Injection)
	// Repository layer
	ingredientRepo := repository.NewIngredientRepository(db)

	// Service layer
	ollamaService := service.NewOllamaService(&cfg.Ollama)

	// Usecase layer
	ingredientUsecase := usecase.NewIngredientUsecase(ingredientRepo)
	recipeUsecase := usecase.NewRecipeUsecase(ingredientRepo, ollamaService)

	// Handler layer
	ingredientHandler := handler.NewIngredientHandler(ingredientUsecase)
	recipeHandler := handler.NewRecipeHandler(recipeUsecase)
	healthHandler := handler.NewHealthHandler(db, ollamaService)

	// Setup Gin router
	router := setupRouter(ingredientHandler, recipeHandler, healthHandler)

	// Create HTTP server
	serverAddr := fmt.Sprintf("%s:%s", cfg.Server.Host, cfg.Server.Port)
	srv := &http.Server{
		Addr:    serverAddr,
		Handler: router,
	}

	// Start server in a goroutine
	go func() {
		logger.Infof("Server is listening on %s", serverAddr)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			logger.Fatalf("Failed to start server: %v", err)
		}
	}()

	// Wait for interrupt signal for graceful shutdown
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	logger.Info("Shutting down server...")

	// Graceful shutdown with timeout
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	if err := srv.Shutdown(ctx); err != nil {
		logger.Errorf("Server forced to shutdown: %v", err)
	}

	logger.Info("Server exited")
}

// setupRouter configures the Gin router with all routes and middleware
func setupRouter(
	ingredientHandler *handler.IngredientHandler,
	recipeHandler *handler.RecipeHandler,
	healthHandler *handler.HealthHandler,
) *gin.Engine {
	// Set Gin mode based on environment
	gin.SetMode(gin.ReleaseMode)

	// Create router
	router := gin.New()

	// Add middleware
	router.Use(gin.Recovery())
	router.Use(logger.GinLogger())

	// Health check endpoints
	router.GET("/health", healthHandler.Health)
	router.GET("/health/db", healthHandler.HealthDB)
	router.GET("/health/ollama", healthHandler.HealthOllama)

	// API routes
	api := router.Group("/api")
	{
		// Ingredient endpoints
		ingredients := api.Group("/ingredients")
		{
			ingredients.POST("", ingredientHandler.CreateIngredient)
			ingredients.GET("", ingredientHandler.GetAllIngredients)
			ingredients.PUT("/:id", ingredientHandler.UpdateIngredient)
			ingredients.DELETE("/:id", ingredientHandler.DeleteIngredient)
		}

		// Recipe endpoints
		recipes := api.Group("/recipes")
		{
			recipes.POST("/suggestion", recipeHandler.GetRecipeSuggestion)
		}
	}

	// Swagger endpoint
	// URL: http://localhost:8080/swagger/index.html
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return router
}
